name: RigelMCMod
main: me.rigelmc.rigelmcmod.RigelMCMod
version: 2.0
description: Plugin for the RigelMC server.
depend: [Aero, WorldEdit]
softdepend: [BukkitTelnet, UMC-Essentials, LibsDisguises]
authors: [Madgeek1450, Prozza, CreeperSeth, AwesomePinch, aggelosQQ, LightWarp, santadeath]

# plugin.yml is no longer used to define commands.
